#setting environment variable for self-signed certificate ignorance
#NOTE THIS LINE NEEDS TO BE DELETED IN RELEASE MODE
#export NODE_TLS_REJECT_UNAUTHORIZED=0

# Defining ports
METAX_PORT=8000
READ_PORT=8001
WRITE_PORT=8002

# Metax self signed certs
SELF_PRIVKEY=../certs/metax.key
SELF_CERT=../certs/metax.crt

# trusting own self signed cert
NODE_EXTRA_CA_CERTS=$SELF_CERT

# Let's Encrypt key and cert
LE_PRIVKEY=../certs/metax.key
LE_CERT=../certs/metax.crt

# Setting strong TLS ciphers
NODE_OPTIONS=--tls-cipher-list='TLS_CHACHA20_POLY1305_SHA256:TLS_AES_256_GCM_SHA384:TLS_AES_128_GCM_SHA256:ECDHE-ECDSA-AES256-GCM-SHA384:ECDHE-RSA-AES256-GCM-SHA384:ECDHE-ECDSA-CHACHA20-POLY1305:ECDHE-RSA-CHACHA20-POLY1305:ECDHE-ECDSA-AES128-GCM-SHA256:ECDHE-RSA-AES128-GCM-SHA256:ECDHE-ECDSA-AES256-SHA384:ECDHE-ECDSA-AES128-SHA256'

current_datetime=$(date +"%Y-%m-%d_%H-%M-%S")
#SITEMAP_UUID=9a3c1be9-32d7-4025-9f03-04d30ce84065-4daefc9f-4349-48cf-89c9-471f48dfb8f1
SITEMAP_UUID=4495be55-3255-11f1-9aa8-bc24117073f9-4495d151-3255-11f1-9667-bc24117073f9
